class Result:
    def __init__(self, scenario_num, equipment):
        self.equipment = equipment
        self.scenario_num = scenario_num

    def calculation(self):
        scenario = 'C' + str(self.scenario_num)
        scnario_value = 1
        mass_all, mass_pf = (22, 33)
        a = [self.equipment[0], self.equipment[1], self.equipment[7], scenario, scnario_value, mass_all, mass_pf]
        spill_fire = list((5, 5, 5, 5))  # результат расчета пожара
        explosion = list((0, 0, 0, 0, 0))  # результат расчета взрыва
        jet_fire = list((0, 0))  # результат расчета факела
        flash_fire = list((0, 0))  # результат расчета вспышки
        toxi = list((0, 0))  # результат расчета токси
        ball_fire = list((0, 0, 0, 0))  # результат расчета шара
        spill_toxi = list((0,))  # результат расчета шара
        damage = list((12, 12, 12, 12, 21, 21))  # результат расчета ущерба
        man = list((3, 4))  # результат расчета погибших/пострадавших
        coll_risk = list((33, 0))  # результат расчета погибших/пострадавших
        math_risk = list((33,))  # результат расчета погибших/пострадавших
        data_1 = a + spill_fire + explosion + jet_fire + flash_fire + toxi + ball_fire + spill_toxi + damage + man + coll_risk + math_risk

        self.scenario_num += 1
        scenario = 'C' + str(self.scenario_num)
        scnario_value = 2
        mass_all, mass_pf = (22, 33)
        a = [self.equipment[0], self.equipment[1], self.equipment[7], scenario, scnario_value, mass_all, mass_pf]
        spill_fire = list((0, 0, 0, 0))  # результат расчета пожара
        explosion = list((6, 6, 6, 6, 6))  # результат расчета взрыва
        jet_fire = list((0, 0))  # результат расчета факела
        flash_fire = list((0, 0))  # результат расчета вспышки
        toxi = list((0, 0))  # результат расчета токси
        ball_fire = list((0, 0, 0, 0))  # результат расчета шара
        spill_toxi = list((0,))  # результат расчета шара
        damage = list((12, 12, 12, 12, 21, 21))  # результат расчета ущерба
        man = list((3, 4))  # результат расчета погибших/пострадавших
        coll_risk = list((33, 0))  # результат расчета погибших/пострадавших
        math_risk = list((33,))  # результат расчета погибших/пострадавших
        data_2 = a + spill_fire + explosion + jet_fire + flash_fire + toxi + ball_fire + spill_toxi + damage + man + coll_risk + math_risk

        self.scenario_num += 1
        scenario = 'C' + str(self.scenario_num)
        scnario_value = 3
        mass_all, mass_pf = (22, 33)
        a = [self.equipment[0], self.equipment[1], self.equipment[7], scenario, scnario_value, mass_all, mass_pf]
        spill_fire = list((0, 0, 0, 0))  # результат расчета пожара
        explosion = list((0, 0, 0, 0, 0))  # результат расчета взрыва
        jet_fire = list((0, 0))  # результат расчета факела
        flash_fire = list((0, 0))  # результат расчета вспышки
        toxi = list((7, 7))  # результат расчета токси
        ball_fire = list((0, 0, 0, 0))  # результат расчета шара
        spill_toxi = list((0,))  # результат расчета шара
        damage = list((12, 12, 12, 12, 21, 21))  # результат расчета ущерба
        man = list((3, 4))  # результат расчета погибших/пострадавших
        coll_risk = list((33, 0))  # результат расчета погибших/пострадавших
        math_risk = list((33,))  # результат расчета погибших/пострадавших
        data_3 = a + spill_fire + explosion + jet_fire + flash_fire + toxi + ball_fire + spill_toxi + damage + man + coll_risk + math_risk

        self.scenario_num += 1
        scenario = 'C' + str(self.scenario_num)
        scnario_value = 3
        mass_all, mass_pf = (22, 33)
        a = [self.equipment[0], self.equipment[1], self.equipment[7], scenario, scnario_value, mass_all, mass_pf]
        spill_fire = list((0, 0, 0, 0))  # результат расчета пожара
        explosion = list((0, 0, 0, 0, 0))  # результат расчета взрыва
        jet_fire = list((15, 15))  # результат расчета факела
        flash_fire = list((0, 0))  # результат расчета вспышки
        toxi = list((0, 0))  # результат расчета токси
        ball_fire = list((0, 0, 0, 0))  # результат расчета шара
        spill_toxi = list((0,))  # результат расчета шара
        damage = list((12, 12, 12, 12, 21, 21))  # результат расчета ущерба
        man = list((3, 4))  # результат расчета погибших/пострадавших
        coll_risk = list((33, 0))  # результат расчета погибших/пострадавших
        math_risk = list((33,))  # результат расчета погибших/пострадавших
        data_4 = a + spill_fire + explosion + jet_fire + flash_fire + toxi + ball_fire + spill_toxi + damage + man + coll_risk + math_risk

        self.scenario_num += 1
        scenario = 'C' + str(self.scenario_num)
        scnario_value = 3
        mass_all, mass_pf = (22, 33)
        a = [self.equipment[0], self.equipment[1], self.equipment[7], scenario, scnario_value, mass_all, mass_pf]
        spill_fire = list((0, 0, 0, 0))  # результат расчета пожара
        explosion = list((0, 0, 0, 0, 0))  # результат расчета взрыва
        jet_fire = list((0, 0))  # результат расчета факела
        flash_fire = list((0, 0))  # результат расчета вспышки
        toxi = list((4, 4))  # результат расчета токси
        ball_fire = list((0, 0, 0, 0))  # результат расчета шара
        spill_toxi = list((0,))  # результат расчета шара
        damage = list((12, 12, 12, 12, 21, 21))  # результат расчета ущерба
        man = list((3, 4))  # результат расчета погибших/пострадавших
        coll_risk = list((33, 0))  # результат расчета погибших/пострадавших
        math_risk = list((33,))  # результат расчета погибших/пострадавших
        data_5 = a + spill_fire + explosion + jet_fire + flash_fire + toxi + ball_fire + spill_toxi + damage + man + coll_risk + math_risk

        self.scenario_num += 1
        scenario = 'C' + str(self.scenario_num)
        scnario_value = 3
        mass_all, mass_pf = (22, 33)
        a = [self.equipment[0], self.equipment[1], self.equipment[7], scenario, scnario_value, mass_all, mass_pf]
        spill_fire = list((0, 0, 0, 0))  # результат расчета пожара
        explosion = list((0, 0, 0, 0, 0))  # результат расчета взрыва
        jet_fire = list((5, 5))  # результат расчета факела
        flash_fire = list((0, 0))  # результат расчета вспышки
        toxi = list((0, 0))  # результат расчета токси
        ball_fire = list((0, 0, 0, 0))  # результат расчета шара
        spill_toxi = list((0,))  # результат расчета шара
        damage = list((12, 12, 12, 12, 21, 21))  # результат расчета ущерба
        man = list((3, 4))  # результат расчета погибших/пострадавших
        coll_risk = list((33, 0))  # результат расчета погибших/пострадавших
        math_risk = list((33,))  # результат расчета погибших/пострадавших
        data_6 = a + spill_fire + explosion + jet_fire + flash_fire + toxi + ball_fire + spill_toxi + damage + man + coll_risk + math_risk

        self.scenario_num += 1
        scenario = 'C' + str(self.scenario_num)
        scnario_value = 3
        mass_all, mass_pf = (22, 33)
        a = [self.equipment[0], self.equipment[1], self.equipment[7], scenario, scnario_value, mass_all, mass_pf]
        spill_fire = list((0, 0, 0, 0))  # результат расчета пожара
        explosion = list((0, 0, 0, 0, 0))  # результат расчета взрыва
        jet_fire = list((0, 0))  # результат расчета факела
        flash_fire = list((8, 8))  # результат расчета вспышки
        toxi = list((0, 0))  # результат расчета токси
        ball_fire = list((0, 0, 0, 0))  # результат расчета шара
        spill_toxi = list((0,))  # результат расчета шара
        damage = list((12, 12, 12, 12, 21, 21))  # результат расчета ущерба
        man = list((3, 4))  # результат расчета погибших/пострадавших
        coll_risk = list((33, 0))  # результат расчета погибших/пострадавших
        math_risk = list((33,))  # результат расчета погибших/пострадавших
        data_7 = a + spill_fire + explosion + jet_fire + flash_fire + toxi + ball_fire + spill_toxi + damage + man + coll_risk + math_risk

        self.scenario_num += 1
        scenario = 'C' + str(self.scenario_num)
        scnario_value = 3
        mass_all, mass_pf = (22, 33)
        a = [self.equipment[0], self.equipment[1], self.equipment[7], scenario, scnario_value, mass_all, mass_pf]
        spill_fire = list((0, 0, 0, 0))  # результат расчета пожара
        explosion = list((0, 0, 0, 0, 0))  # результат расчета взрыва
        jet_fire = list((0, 0))  # результат расчета факела
        flash_fire = list((0, 0))  # результат расчета вспышки
        toxi = list((1, 1))  # результат расчета токси
        ball_fire = list((0, 0, 0, 0))  # результат расчета шара
        spill_toxi = list((0,))  # результат расчета шара
        damage = list((12, 12, 12, 12, 21, 21))  # результат расчета ущерба
        man = list((3, 4))  # результат расчета погибших/пострадавших
        coll_risk = list((33, 0))  # результат расчета погибших/пострадавших
        math_risk = list((33,))  # результат расчета погибших/пострадавших
        data_8 = a + spill_fire + explosion + jet_fire + flash_fire + toxi + ball_fire + spill_toxi + damage + man + coll_risk + math_risk

        return (data_1, data_2, data_3, data_4, data_5, data_6, data_7, data_8)